# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoitem', '0003_auto_20171108_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItems',
            new_name='TodoItem',
        ),
    ]
