# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoitem', '0004_auto_20171108_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(default='medium', max_length=6),
            preserve_default=False,
        ),
    ]
